# Generated by Django 5.2 on 2025-04-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.CharField(blank=True, help_text='Enter a unique code', max_length=8, null=True, unique=True),
        ),
    ]
