# Generated by Django 5.2 on 2025-04-16 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='code',
            field=models.CharField(blank=True, help_text='Enter a unique 8 Character code', max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Code must only contain letters (no numbers, symbols, or spaces).', regex=['a-zA-Z'])]),
        ),
    ]
