# Generated by Django 5.1.7 on 2025-04-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_question_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='published_date',
            new_name='pub_date',
        ),
    ]
