# Generated by Django 5.2 on 2025-04-23 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_published_date_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
